name: Build ASL reference

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'internal/bento.mll'
      - 'asllib/doc/**'
      - 'asllib/aslspec/**'
      - '.github/workflows/build-asl-reference.yml'

permissions: read-all

# Copy-pasted from https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  make-asldoc:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest-full

    env:
      OPAMROOTISOK: 1 # Suppress warnings about running opam as root

    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y gcc libgmp-dev pkg-config python3 bzip2

      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: dune,zarith,menhir,conf-which
          opam-disable-sandboxing: true
          dune-cache: true

      - name: Mark working directory as "safe"
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Install opam dependencies
        run: opam install . --deps-only --yes

      - name: Build ASL Reference
        run: opam exec -- make asldoc

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
         name: ASL Reference Document
         path: asllib/doc/ASLReference.pdf
