name: Build WWW

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml 5
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.0
      - run: |
          opam install dune menhir zarith js_of_ocaml.5.4.0 js_of_ocaml-ppx zarith_stubs_js
          opam exec -- make Version.ml
          opam exec -- dune build tools/cat2html.exe
          opam exec -- make -C herd-www
      - name: www
        uses: actions/upload-artifact@v4
        with:
          name: www
          path: |
            herd-www/www
