name: Check Build WWW

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Optional PR number to build (uses refs/pull/<n>/head)"
        required: false
        type: string
  schedule:
      - cron: '0 8 * * 0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - "5.1"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR head ref (if provided)
        if: ${{ github.event.inputs.pr_number != '' }}
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.inputs.pr_number }}/head

      - name: Checkout default branch
        if: ${{ github.event.inputs.pr_number == '' }}
        uses: actions/checkout@v4

      - name: Set-up OCaml 5
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - run: |
          opam install dune menhir zarith js_of_ocaml js_of_ocaml-ppx zarith_stubs_js
          opam exec -- make Version.ml
          opam exec -- dune build tools/cat2html.exe
          opam exec -- make -C herd-www
